//
//  TestProtocols.swift
//  APP_CTCT
//
//  Created vinova on 11/8/18.
//  Copyright © 2018 vinova. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol TestWireframeProtocol: class {

}
//MARK: Presenter -
protocol TestPresenterProtocol: class {

    var interactor: TestInteractorInputProtocol? { get set }
     func notifyInteratorGetQuestion()
}

//MARK: Interactor -
protocol TestInteractorOutputProtocol: class {
    func returnQuestionSuccess(data: [QuestionText])
    /* Interactor -> Presenter */
}

protocol TestInteractorInputProtocol: class {

    var presenter: TestInteractorOutputProtocol?  { get set }
    func notifyInteratorGetQuestion()
    /* Presenter -> Interactor */
    
}

//MARK: View -
protocol TestViewProtocol: class {

    var presenter: TestPresenterProtocol?  { get set }
    func getQuestionSuccess(data:[QuestionText])
    /* Presenter -> ViewController */
}
