//
//  TestInteractor.swift
//  APP_CTCT
//
//  Created vinova on 11/8/18.
//  Copyright © 2018 vinova. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class TestInteractor: TestInteractorInputProtocol {

    weak var presenter: TestInteractorOutputProtocol?
    
    func notifyInteratorGetQuestion() {
        var arrData : [QuestionText] = []
        arrData.append(QuestionText(index: 2, content_question: "Chau ngoc nguyen nguyen ngoc chau ngoc chau nguyen", question_a: "a nguyen nguyen nguyen nsdadasdasdsadasdasdasdasdsadasdsadsadasdsadadadasd", question_b: "b", question_c: "c", question_d: "d"))
        arrData.append(QuestionText(index: 2, content_question: "Chau ngoc nguyen nguyen ngoc chau ngoc chau nguyen", question_a: "a", question_b: "b", question_c: "c", question_d: "d"))
        arrData.append(QuestionText(index: 2, content_question: "Chau ngoc nguyen nguyen ngoc chau ngoc chau nguyen", question_a: "a", question_b: "b", question_c: "c", question_d: "d"))
        arrData.append(QuestionText(index: 2, content_question: "Chau ngoc nguyen nguyen ngoc chau ngoc chau nguyen", question_a: "a", question_b: "b", question_c: "c", question_d: "d"))
        arrData.append(QuestionText(index: 2, content_question: "Chau ngoc nguyen nguyen ngoc chau ngoc chau nguyen", question_a: "a", question_b: "b", question_c: "c", question_d: "d"))
        arrData.append(QuestionText(index: 2, content_question: "Chau ngoc nguyen nguyen ngoc chau ngoc chau nguyen", question_a: "a", question_b: "b", question_c: "c", question_d: "d"))
        arrData.append(QuestionText(index: 2, content_question: "Chau ngoc nguyen nguyen ngoc chau ngoc chau nguyen", question_a: "a", question_b: "b", question_c: "c", question_d: "d"))
        arrData.append(QuestionText(index: 2, content_question: "Chau ngoc nguyen nguyen ngoc chau ngoc chau nguyen", question_a: "a", question_b: "b", question_c: "c", question_d: "d"))
        arrData.append(QuestionText(index: 2, content_question: "Chau ngoc nguyen nguyen ngoc chau ngoc chau nguyen", question_a: "a", question_b: "b", question_c: "c", question_d: "d"))
        arrData.append(QuestionText(index: 2, content_question: "Chau ngoc nguyen nguyen ngoc chau ngoc chau nguyen", question_a: "a", question_b: "b", question_c: "c", question_d: "d"))
        arrData.append(QuestionText(index: 2, content_question: "Chau ngoc nguyen nguyen ngoc chau ngoc chau nguyen", question_a: "a", question_b: "b", question_c: "c", question_d: "d"))
        arrData.append(QuestionText(index: 2, content_question: "Chau ngoc nguyen nguyen ngoc chau ngoc chau nguyen", question_a: "a", question_b: "b", question_c: "c", question_d: "d"))
        presenter?.returnQuestionSuccess(data: arrData)
        
    }
}
