//
//  ChangePasswordPresenter.swift
//  APP_CTCT
//
//  Created vinova on 11/15/18.
//  Copyright © 2018 vinova. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class ChangePasswordPresenter: ChangePasswordPresenterProtocol, ChangePasswordInteractorOutputProtocol {

    weak private var view: ChangePasswordViewProtocol?
    var interactor: ChangePasswordInteractorInputProtocol?
    private let router: ChangePasswordWireframeProtocol

    init(interface: ChangePasswordViewProtocol, interactor: ChangePasswordInteractorInputProtocol?, router: ChangePasswordWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }
    
    func currentPassEmpty() {
        view?.currentPassEmpty()
    }
    
    func newPassEmpty() {
        view?.newPassEmpty()
    }
    
    func confirmPassEmpty() {
        view?.confirmPassEmpty()
    }
    
    func currentPassEqualNewPass() {
        view?.currentPassEqualNewPass()
    }
    
    func newPassDiffenceConfirmPass() {
        view?.newPassDiffenceConfirmPass()
    }
    
    func successed() {
        view?.successed()
    }
    
    func failedNetwork() {
        
    }
    
    func notifyInterator(currentPass: String?, newPass: String?, confirmPass: String?) {
        interactor?.notifyInterator(currentPass: currentPass, newPass: newPass, confirmPass: confirmPass)
    }
    func backRoot() {
        router.backRoot()
    }
}
