//
//  ChangePasswordInteractor.swift
//  APP_CTCT
//
//  Created vinova on 11/15/18.
//  Copyright © 2018 vinova. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class ChangePasswordInteractor: ChangePasswordInteractorInputProtocol {

    weak var presenter: ChangePasswordInteractorOutputProtocol?
    
    func notifyInterator(currentPass: String?, newPass: String?, confirmPass: String?) {
        guard let current = currentPass else { return }
        
        guard let new = newPass else { return }
        
        guard let confirm = confirmPass else { return }
        
        if current == ""{
            presenter?.currentPassEmpty()
            return
        }
        if new == "" {
            presenter?.newPassEmpty()
            return
        }
        if confirm == ""{
            presenter?.confirmPassEmpty()
        }
        if current == new {
            presenter?.currentPassEqualNewPass()
            return
        }
        if new == confirm{
            presenter?.newPassDiffenceConfirmPass()
            return
        }
        //call API
        presenter?.successed()
    }
    
}
