//
//  ProfileInteractor.swift
//  APP_CTCT
//
//  Created vinova on 11/7/18.
//  Copyright © 2018 vinova. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class ProfileInteractor: ProfileInteractorInputProtocol {

    weak var presenter: ProfileInteractorOutputProtocol?
}
