//
//  InfoBKUInteractor.swift
//  APP_CTCT
//
//  Created vinova on 11/22/18.
//  Copyright © 2018 vinova. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class InfoBKUInteractor: InfoBKUInteractorInputProtocol {

    weak var presenter: InfoBKUInteractorOutputProtocol?
}
