//
//  InfoBKURouter.swift
//  APP_CTCT
//
//  Created vinova on 11/22/18.
//  Copyright © 2018 vinova. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class InfoBKURouter: InfoBKUWireframeProtocol {

    weak var viewController: UIViewController?

    static func createModule() -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = InfoBKUViewController(nibName: nil, bundle: nil)
        let interactor = InfoBKUInteractor()
        let router = InfoBKURouter()
        let presenter = InfoBKUPresenter(interface: view, interactor: interactor, router: router)

        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view

        return view
    }
}
