//
//  InfoBKUViewController.swift
//  APP_CTCT
//
//  Created vinova on 11/22/18.
//  Copyright © 2018 vinova. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit
import WebKit

class InfoBKUViewController: BaseViewController, InfoBKUViewProtocol {

	var presenter: InfoBKUPresenterProtocol?
    @IBOutlet weak var wkView: WKWebView!
    
    override func viewDidLoad() {
        super.viewDidLoad()
        setupView()
    }
    
    override func setupNavigation() {
        super.setupNavigation()
        self.addBackNavigation()
    }
    
    func setupView(){
        wkView.navigationDelegate = self
        ViewIndicator.shared.showProgressView()
        wkView.readPDF(link: Strings.links.linkBKU)
    }
}
extension InfoBKUViewController: WKNavigationDelegate{
    func webView(_ webView: WKWebView, didFinish navigation: WKNavigation!) {
        ViewIndicator.shared.hideProgressView()
    }
}
