//
//  InfoBKUProtocols.swift
//  APP_CTCT
//
//  Created vinova on 11/22/18.
//  Copyright © 2018 vinova. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol InfoBKUWireframeProtocol: class {
   
}
//MARK: Presenter -
protocol InfoBKUPresenterProtocol: class {

    var interactor: InfoBKUInteractorInputProtocol? { get set }
    
}

//MARK: Interactor -
protocol InfoBKUInteractorOutputProtocol: class {

    /* Interactor -> Presenter */
}

protocol InfoBKUInteractorInputProtocol: class {

    var presenter: InfoBKUInteractorOutputProtocol?  { get set }

    /* Presenter -> Interactor */
}

//MARK: View -
protocol InfoBKUViewProtocol: class {

    var presenter: InfoBKUPresenterProtocol?  { get set }

    /* Presenter -> ViewController */
}
