//
//  PDFInteractor.swift
//  APP_CTCT
//
//  Created vinova on 11/8/18.
//  Copyright © 2018 vinova. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class PDFInteractor: PDFInteractorInputProtocol {

    weak var presenter: PDFInteractorOutputProtocol?
}
