//
//  PDFViewController.swift
//  APP_CTCT
//
//  Created vinova on 11/8/18.
//  Copyright © 2018 vinova. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit
import WebKit

class PDFViewController: UIViewController, PDFViewProtocol {

	var presenter: PDFPresenterProtocol?


    @IBOutlet weak var webKit: WKWebView!
    
    override func viewDidLoad() {
        super.viewDidLoad()
        webKit.navigationDelegate = self
        ViewIndicator.shared.showProgressView()
        webKit.readPDF(link: "http://www.axmag.com/download/pdfurl-guide.pdf")
    }
}
extension PDFViewController : WKNavigationDelegate{
    func webView(_ webView: WKWebView, didFinish navigation: WKNavigation!) {
        ViewIndicator.shared.hideProgressView()
    }
}
