//
//  MemberCTCTInteractor.swift
//  APP_CTCT
//
//  Created vinova on 11/15/18.
//  Copyright © 2018 vinova. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class MemberCTCTInteractor: MemberCTCTInteractorInputProtocol {

    weak var presenter: MemberCTCTInteractorOutputProtocol?
}
