//
//  MemberCTCTPresenter.swift
//  APP_CTCT
//
//  Created vinova on 11/15/18.
//  Copyright © 2018 vinova. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class MemberCTCTPresenter: MemberCTCTPresenterProtocol, MemberCTCTInteractorOutputProtocol {

    weak private var view: MemberCTCTViewProtocol?
    var interactor: MemberCTCTInteractorInputProtocol?
    private let router: MemberCTCTWireframeProtocol

    init(interface: MemberCTCTViewProtocol, interactor: MemberCTCTInteractorInputProtocol?, router: MemberCTCTWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

}
