//
//  MemberCTCTProtocols.swift
//  APP_CTCT
//
//  Created vinova on 11/15/18.
//  Copyright © 2018 vinova. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol MemberCTCTWireframeProtocol: class {

}
//MARK: Presenter -
protocol MemberCTCTPresenterProtocol: class {

    var interactor: MemberCTCTInteractorInputProtocol? { get set }
}

//MARK: Interactor -
protocol MemberCTCTInteractorOutputProtocol: class {

    /* Interactor -> Presenter */
}

protocol MemberCTCTInteractorInputProtocol: class {

    var presenter: MemberCTCTInteractorOutputProtocol?  { get set }

    /* Presenter -> Interactor */
}

//MARK: View -
protocol MemberCTCTViewProtocol: class {

    var presenter: MemberCTCTPresenterProtocol?  { get set }

    /* Presenter -> ViewController */
}
