//
//  SettingPresenter.swift
//  APP_CTCT
//
//  Created vinova on 11/14/18.
//  Copyright © 2018 vinova. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class SettingPresenter: SettingPresenterProtocol, SettingInteractorOutputProtocol {

    weak private var view: SettingViewProtocol?
    var interactor: SettingInteractorInputProtocol?
    private let router: SettingWireframeProtocol

    init(interface: SettingViewProtocol, interactor: SettingInteractorInputProtocol?, router: SettingWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }
    
    func openInfoBKU() {
        router.openInfoBKU()
    }
    
    func openChangePassword() {
        router.openChangePassword()
    }
}
