//
//  SettingProtocols.swift
//  APP_CTCT
//
//  Created vinova on 11/14/18.
//  Copyright © 2018 vinova. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol SettingWireframeProtocol: class {
    func openInfoBKU()
    func openChangePassword()
}
//MARK: Presenter -
protocol SettingPresenterProtocol: class {

    var interactor: SettingInteractorInputProtocol? { get set }
    func openInfoBKU()
    func openChangePassword()
}

//MARK: Interactor -
protocol SettingInteractorOutputProtocol: class {

    /* Interactor -> Presenter */
}

protocol SettingInteractorInputProtocol: class {

    var presenter: SettingInteractorOutputProtocol?  { get set }

    /* Presenter -> Interactor */
}

//MARK: View -
protocol SettingViewProtocol: class {

    var presenter: SettingPresenterProtocol?  { get set }

    /* Presenter -> ViewController */
}
