//
//  SettingInteractor.swift
//  APP_CTCT
//
//  Created vinova on 11/14/18.
//  Copyright © 2018 vinova. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class SettingInteractor: SettingInteractorInputProtocol {

    weak var presenter: SettingInteractorOutputProtocol?
}
