//
//  ForgotPasswordPresenter.swift
//  APP_CTCT
//
//  Created vinova on 11/20/18.
//  Copyright © 2018 vinova. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class ForgotPasswordPresenter: ForgotPasswordPresenterProtocol, ForgotPasswordInteractorOutputProtocol {

    weak private var view: ForgotPasswordViewProtocol?
    var interactor: ForgotPasswordInteractorInputProtocol?
    private let router: ForgotPasswordWireframeProtocol

    init(interface: ForgotPasswordViewProtocol, interactor: ForgotPasswordInteractorInputProtocol?, router: ForgotPasswordWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

}
