//
//  ForgotPasswordProtocols.swift
//  APP_CTCT
//
//  Created vinova on 11/20/18.
//  Copyright © 2018 vinova. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol ForgotPasswordWireframeProtocol: class {

}
//MARK: Presenter -
protocol ForgotPasswordPresenterProtocol: class {

    var interactor: ForgotPasswordInteractorInputProtocol? { get set }
}

//MARK: Interactor -
protocol ForgotPasswordInteractorOutputProtocol: class {

    /* Interactor -> Presenter */
}

protocol ForgotPasswordInteractorInputProtocol: class {

    var presenter: ForgotPasswordInteractorOutputProtocol?  { get set }

    /* Presenter -> Interactor */
}

//MARK: View -
protocol ForgotPasswordViewProtocol: class {

    var presenter: ForgotPasswordPresenterProtocol?  { get set }

    /* Presenter -> ViewController */
}
