//
//  ForgotPasswordRouter.swift
//  APP_CTCT
//
//  Created vinova on 11/20/18.
//  Copyright © 2018 vinova. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class ForgotPasswordRouter: ForgotPasswordWireframeProtocol {

    weak var viewController: UIViewController?

    static func createModule(isPhone: Bool) -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = ForgotPasswordViewController(nibName: nil, bundle: nil)
        let interactor = ForgotPasswordInteractor()
        let router = ForgotPasswordRouter()
        let presenter = ForgotPasswordPresenter(interface: view, interactor: interactor, router: router)
        view.isPhone = isPhone
        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view

        return view
    }
}
