//
//  ForgotPasswordViewController.swift
//  APP_CTCT
//
//  Created vinova on 11/20/18.
//  Copyright © 2018 vinova. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit
import SinchVerification
import FirebaseAuth

class ForgotPasswordViewController: PhoneNumberEntryVC, ForgotPasswordViewProtocol {
    
    @IBOutlet weak var tfConfirmCode: ViewTextField!
    @IBOutlet weak var topButtonConfirm: NSLayoutConstraint!
    @IBOutlet weak var btConfirm: CustomButton!
    @IBOutlet weak var tfPhoneNumber: CustomTextFieldIcon!
    var isPhone = false
    @IBOutlet weak var imgCancel: UIImageView!
    
    var presenter: ForgotPasswordPresenterProtocol?

	override func viewDidLoad() {
        super.viewDidLoad()
        setupView()
    }
    
    func setupView(){
        self.navigationController?.navigationBar.topItem?.title = Strings.Navigation.forgotPassword
        imgCancel.isUserInteractionEnabled = true
        imgCancel.addGestureRecognizer(UITapGestureRecognizer(target: self, action: #selector(cancel)))
        if (isPhone){
            tfPhoneNumber.setupTextField(image: #imageLiteral(resourceName: "phonenumber"), hint: Strings.TextField.phoneNumber)
            tfPhoneNumber.setKeyboardNumber()
        }
        else{
            tfPhoneNumber.setupTextField(image: #imageLiteral(resourceName: "user"), hint: Strings.TextField.email)
        }
        btConfirm.setTextButton(tempText: Strings.Button.confirm)
        btConfirm.addGestureRecognizer(UITapGestureRecognizer(target: self, action: #selector(confirm)))
        tfConfirmCode.setDataView(textLabel: Strings.TextField.confirmCode, placeText: Strings.TextField.confirmCode)
    }
    
    @objc func confirm(){
        ViewIndicator.shared.showProgressView()
        if tfConfirmCode.getTextTextField() != "" {
            verificationCode(code: tfConfirmCode.getTextTextField() ?? "")
            
            return
        }
        if (isPhone){
            sendSMS()
            return
        }
        sendEmail()
    }
    
    private func verificationCode(code: String){
        verification.verify(code) { (isSuccess, error) in
            if isSuccess {
                ViewIndicator.shared.hideProgressView()
                AlterController.showAlter(vc: self, message: "Code Successed")

            } else {
                ViewIndicator.shared.hideProgressView()
                AlterController.showAlter(vc: self, message: "Code Failed")
            }
        }
    }
    
    private func sendSMS(){
        if let phone = tfPhoneNumber.getText() {
            verification = SMSVerification(Strings.Sinch.phone, phoneNumber: phone.converPhoneNumber())
            verification.initiate { (result, error) in
                ViewIndicator.shared.hideProgressView()
                if error != nil {
                    AlterController.showAlter(vc: self, message: "Phone Number Error")
                }
                if result.success {
                    AlterController.showAlter(vc: self, message: "Please check your phone")
                    self.uiPhoneSendMessage()
                }
            }
        }
    }
    
    private func uiPhoneSendMessage(){
        UIView.animate(withDuration: 0.5) {
            self.topButtonConfirm.constant = 90
            self.tfConfirmCode.isHidden = false
        }
    }
    
    private func sendEmail(){
        
    }
    
    @objc func cancel(){
        self.dismiss(animated: true, completion: nil)
    }
}
