//
//  ConfirmPhoneNumberRouter.swift
//  APP_CTCT
//
//  Created vinova on 11/20/18.
//  Copyright © 2018 vinova. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class ConfirmPhoneNumberRouter: ConfirmPhoneNumberWireframeProtocol {

    weak var viewController: UIViewController?

    static func createModule() -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = ConfirmPhoneNumberViewController(nibName: nil, bundle: nil)
        let interactor = ConfirmPhoneNumberInteractor()
        let router = ConfirmPhoneNumberRouter()
        let presenter = ConfirmPhoneNumberPresenter(interface: view, interactor: interactor, router: router)

        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view

        return view
    }
}
