//
//  ConfirmPhoneNumberPresenter.swift
//  APP_CTCT
//
//  Created vinova on 11/20/18.
//  Copyright © 2018 vinova. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class ConfirmPhoneNumberPresenter: ConfirmPhoneNumberPresenterProtocol, ConfirmPhoneNumberInteractorOutputProtocol {

    weak private var view: ConfirmPhoneNumberViewProtocol?
    var interactor: ConfirmPhoneNumberInteractorInputProtocol?
    private let router: ConfirmPhoneNumberWireframeProtocol

    init(interface: ConfirmPhoneNumberViewProtocol, interactor: ConfirmPhoneNumberInteractorInputProtocol?, router: ConfirmPhoneNumberWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

}
