//
//  ConfirmPhoneNumberViewController.swift
//  APP_CTCT
//
//  Created vinova on 11/20/18.
//  Copyright © 2018 vinova. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class ConfirmPhoneNumberViewController: UIViewController, ConfirmPhoneNumberViewProtocol {
    
    @IBOutlet weak var btnConfirm: CustomButton!
    @IBOutlet weak var lblSendCode: UILabel!
    @IBOutlet weak var codeVerification: ViewTextField!
    @IBOutlet weak var newPhone: ViewTextField!
    @IBOutlet weak var currentPhone: ViewTextField!
    
    var presenter: ConfirmPhoneNumberPresenterProtocol?

	override func viewDidLoad() {
        super.viewDidLoad()
        setupView()
    }
    
    func setupView(){
        self.navigationController?.navigationBar.topItem?.title = Strings.Navigation.phoneNumber
        currentPhone.setDataView(textLabel: "Current Phone", placeText: "Current Phone")
        newPhone.setDataView(textLabel: "New Phone", placeText: "New Phone")
        codeVerification.setDataView(textLabel: "Code Verification", placeText: "Code Verification")
        btnConfirm.setTextButton(tempText: "Confirm")
        lblSendCode.isUserInteractionEnabled = true
        lblSendCode.addGestureRecognizer(UITapGestureRecognizer(target: self, action: #selector(sendCode)))
        btnConfirm.addGestureRecognizer(UITapGestureRecognizer(target: self, action: #selector(confirm)))
    }
    
    @objc func sendCode(){
        
    }
    
    @objc func confirm(){
        
    }
}
