//
//  ConfirmPhoneNumberInteractor.swift
//  APP_CTCT
//
//  Created vinova on 11/20/18.
//  Copyright © 2018 vinova. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class ConfirmPhoneNumberInteractor: ConfirmPhoneNumberInteractorInputProtocol {

    weak var presenter: ConfirmPhoneNumberInteractorOutputProtocol?
}
